### PR TITLE
Make Entwine delete button selector more specific

### LINKED ISSUE #3: Confirmation alert not triggered (SS 4.8)
Probably the Entwine selector is less specific than some other selector hence the confirm() doesn't get shown.

### PR DESCRIPTION
**Pull request by micschk**
Fixes https://github.com/dnadesign/gridfield-bulk-delete/issues/3

### CODE REVIEW

**Comment by alex-dna** [comment]
Sorry, this still doesn't quite work for me. Will do some more testing.

**Comment by micschk** [comment]
What doesn't work? The confirm dialog still doesn't get triggered you mean?

I'm using this ('#Root .bulkdelete_button') selector succesfully in the UserForms context, so that's in the CMS page Ui. Did you maybe test this in some other context I didn't consider?

**Comment by micschk** [comment]
Ah, I see there's no '#Root' element in ModelAdmins, probably you tested in that.
Modified the selector to work in both now: `$('#Form_EditForm .bulkdelete_button')`

**Comment by micschk** [comment]
Oh, and if & after merging a tag release would be nice :-)
 Thx, very useful module(s)!

**Comment by alex-dna** [comment]
thanks @micschk , everything has been merged now and version 1.2 has been created. Thanks for your contribution.

**Pull request merged**
